plugins {
    id 'com.android.application'
}

android {
    namespace 'com.emma.robot.control'
    compileSdk 34

    defaultConfig {
        applicationId 'com.emma.robot.control'
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName '0.1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation files('libs/aoborobotsdk-v2.1.2.aar')
}
